service: hudhomes-alerts

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  environment:
    MAILER_USER: ''
    MAILER_PASS: ''

functions:
  gethudhomes:
    handler: handler.gethudhomes
    events:
      - schedule: rate(6 hours)
